#!/bin/sh

case "$1" in 
start)
   if [ -e /var/run/zorp.pid ]; then
      echo zorp is running, pid=`cat /var/run/zorp.pid`
      exit 1
   else
      zorp -f /etc/zorp/global.cfg -f /etc/zorp/zorp.cfg -p /var/run/zorp.pid
   fi   
   ;;
stop)
   kill -USR1 `cat /var/run/zorp.pid`
   rm /var/run/zorp.pid
   ;;
restart)
   $0 apply
   ;;
reload)
   $0 apply
   ;;
status)
   if [ -e /var/run/zorp.pid ]; then
      echo zorp is running, pid=`cat /var/run/zorp.pid`
   else
      echo zorp is NOT running
      exit 1
   fi
   ;;
apply)   
   if [ -e /var/run/zorp.pid ]; then
      zorp -f /etc/zorp/global.cfg -f /etc/zorp/zorp.cfg -p /var/run/zorp.pid -sf $(cat /var/run/zorp.pid)
   else
      $0 start
   fi
   ;;
push_apply)   
   $0 apply
   ;;
validate)   
   zorp -c -f /etc/zorp/global.cfg -f /etc/zorp/zorp.cfg
   ;;
*)
   echo "Usage: $0 {start|stop|status|reload}"
esac

exit 0